export interface Lesson {
  id: string; grade: number; title: string; domain: string; objective: string;
  concept: string; offline: string; prerequisite: string | null;
}
const definitions: [number, string, string, string, string, string, string, string | null][] = [
  [1,"menghitung","Menghitung benda","Bilangan","Menghubungkan benda dengan banyaknya.","Satu benda mendapat satu nama bilangan. Bilangan terakhir menyatakan banyaknya seluruh benda.","Susun sendok di meja. Sentuh setiap sendok satu kali sambil menghitung.",null],
  [1,"menjumlah","Menggabungkan kelompok","Operasi","Memahami penjumlahan sebagai penggabungan.","Dua kelompok digabung. Setiap benda dihitung sekali; tidak ada benda yang hilang.","Gabungkan dua kelompok tutup botol, lalu ceritakan apa yang berubah.","menghitung"],
  [1,"mengurangi","Mengambil sebagian","Operasi","Memahami pengurangan sebagai mengambil sebagian.","Mulai dari kelompok utuh, ambil sebagian, lalu hitung yang masih ada.","Letakkan delapan benda. Ambil tiga, lalu jelaskan arti sisanya.","menghitung"],
  [1,"membandingkan","Lebih banyak dan lebih sedikit","Bilangan","Membandingkan dua banyak benda.","Pasangkan satu benda dari tiap kelompok. Kelompok yang memiliki sisa benda lebih banyak.","Bandingkan dua kelompok kancing dengan memasangkan satu-satu.","menghitung"],
  [1,"bangun","Mengenal sisi bangun","Geometri","Menghitung sisi lurus bangun datar.","Sisi adalah ruas lurus pada tepi bangun. Mulai dari satu sisi, lalu ikuti tepinya sampai kembali.","Jiplak kotak dan segitiga; telusuri setiap sisinya dengan jari.",null],
  [2,"nilai-tempat","Puluhan dan satuan","Bilangan","Memahami sepuluh satuan sebagai satu puluhan.","Nilai digit bergantung pada tempatnya. Tiga puluhan berarti tiga kelompok berisi sepuluh.","Ikat sedotan dalam kelompok sepuluh dan sisakan beberapa sedotan lepas.","menghitung"],
  [2,"tambah-puluhan","Penjumlahan dua digit","Operasi","Menjumlah menurut nilai tempat, termasuk membuat puluhan baru.","Gabungkan satuan dengan satuan dan puluhan dengan puluhan. Sepuluh satuan dapat ditukar menjadi satu puluhan.","Gunakan ikatan sepuluh sedotan untuk memperagakan 27 ditambah 15.","nilai-tempat"],
  [2,"kurang-puluhan","Pengurangan dua digit","Operasi","Mengurai satu puluhan saat satuan tidak cukup.","Jika satuan tidak cukup, tukar satu puluhan menjadi sepuluh satuan. Jumlah awal tetap sama.","Peragakan 32 dikurangi 15 dengan ikatan sedotan dan sedotan lepas.","nilai-tempat"],
  [2,"waktu","Lama kegiatan","Pengukuran","Menghubungkan waktu mulai, waktu akhir, dan durasi.","Durasi adalah jarak waktu dari mulai sampai selesai, bukan waktu pada jam akhir.","Catat jam mulai dan selesai membaca. Hitung berapa jam yang berlalu.","mengurangi"],
  [2,"panjang","Mengukur panjang","Pengukuran","Mengukur dengan unit sama tanpa celah.","Unit pengukuran disusun berurutan, sama panjang, tanpa celah atau tumpang tindih.","Ukur buku dengan potongan kertas sama panjang. Bandingkan dengan penggaris.","menghitung"],
  [3,"perkalian","Kelompok sama banyak","Operasi","Memahami perkalian sebagai kelompok sama besar.","Jumlah kelompok dikalikan isi tiap kelompok. Semua kelompok memiliki isi yang sama.","Susun tiga piring berisi empat kancing per piring, lalu hitung seluruhnya.","menjumlah"],
  [3,"pembagian","Berbagi sama rata","Operasi","Memahami pembagian sebagai berbagi adil.","Bagikan seluruh benda ke kelompok sama banyak sampai tidak ada sisa.","Bagikan dua belas benda ke tiga wadah sama rata.","perkalian"],
  [3,"pecahan","Bagian dari satu utuh","Pecahan","Menyebut bagian terpilih dari bagian sama besar.","Penyebut menyatakan seluruh bagian sama besar. Pembilang menyatakan bagian yang dipilih.","Lipat kertas menjadi empat bagian sama besar; tandai beberapa bagiannya.","pembagian"],
  [3,"keliling","Mengelilingi persegi panjang","Geometri","Membedakan panjang tepi dari luas.","Keliling adalah jumlah panjang seluruh sisi di tepi. Dua sisi panjang dan dua sisi lebar dihitung.","Telusuri tepi buku dengan benang, lalu ukur panjang benangnya.","menjumlah"],
  [3,"diagram","Membaca diagram batang","Data","Mengambil informasi banyaknya dari diagram.","Setiap unit tinggi batang mewakili satu data. Bandingkan tinggi batang, bukan lebarnya.","Buat diagram banyak pensil, buku, dan penghapus di meja.","membandingkan"],
  [4,"pecahan-senilai","Pecahan yang senilai","Pecahan","Memahami bagian yang sama meski pembagian lebih kecil.","Membagi setiap bagian menjadi dua menggandakan pembilang dan penyebut. Besar bagian terpilih tetap sama.","Bandingkan kertas dengan setengah terpilih dan kertas dengan dua perempat terpilih.","pecahan"],
  [4,"luas","Mengisi persegi panjang","Geometri","Memahami luas sebagai banyak persegi satuan.","Luas menghitung kotak satuan yang menutup permukaan. Baris dikalikan kotak dalam tiap baris.","Tutupi buku dengan kotak kertas sama besar tanpa celah.","perkalian"],
  [4,"sudut","Membandingkan sudut","Geometri","Memahami besar putaran sudut siku-siku.","Satu putaran penuh 360 derajat. Seperempat putaran membentuk sudut siku-siku.","Putar pensil dari mendatar ke tegak; bandingkan dengan sudut pojok buku.","pembagian"],
  [4,"faktor","Mencari faktor bilangan","Bilangan","Menemukan bilangan yang membagi tanpa sisa.","Faktor membagi suatu bilangan menjadi kelompok utuh tanpa sisa. Pasangan faktor memiliki hasil kali sama.","Susun dua belas benda menjadi persegi panjang dengan jumlah baris berbeda.","pembagian"],
  [4,"satuan","Meter dan sentimeter","Pengukuran","Mengubah unit tanpa mengubah panjang.","Satu meter memuat seratus sentimeter. Mengganti unit tidak membuat benda lebih panjang.","Temukan tanda 100 cm pada meteran dan cocokkan dengan satu meter.","panjang"],
  [5,"desimal","Persepuluhan dalam desimal","Pecahan","Menghubungkan pecahan persepuluh dengan desimal.","Satu utuh dibagi sepuluh bagian sama besar. Satu bagian ditulis 0,1.","Bagi pita menjadi sepuluh bagian sama besar dan tandai beberapa bagian.","pecahan"],
  [5,"tambah-pecahan","Menjumlah pecahan","Pecahan","Menjumlah bagian dengan penyebut sama.","Jika ukuran bagiannya sama, jumlahkan banyak bagian terpilih. Penyebut tidak dijumlahkan.","Gabungkan satu perdelapan dan tiga perdelapan dari dua pita dengan panjang utuh sama.","pecahan"],
  [5,"volume","Mengisi kotak dengan kubus","Geometri","Memahami volume sebagai banyak kubus satuan.","Hitung kubus pada satu lapisan, lalu kalikan dengan banyak lapisan. Setiap kubus mengisi ruang yang sama.","Susun kubus mainan menjadi kotak dua lapisan, lalu hitung kubus tiap lapisan.","luas"],
  [5,"persen","Persen berarti per seratus","Pecahan","Menghubungkan bagian per seratus dan persentase.","Persen menyatakan bagian dari seratus. Lima puluh persen adalah setengah dari satu utuh.","Buat kotak seratus bagian; tandai dua puluh lima bagiannya.","pecahan-senilai"],
  [5,"rata-rata","Meratakan data","Data","Memahami rata-rata sebagai pembagian total secara rata.","Jumlahkan semua nilai, lalu bagi dengan banyak data. Rata-rata dapat dibayangkan sebagai hasil meratakan.","Bagikan ulang tiga tumpukan benda agar tiap tumpukan sama banyak.","pembagian"],
  [6,"perbandingan","Perbandingan senilai","Bilangan","Menjaga hubungan dua besaran.","Jika jumlah kelompok dikali dua, kebutuhan tiap kelompok juga dikali dua. Hubungannya tetap.","Jika dua gelas butuh empat sendok sirup, peragakan kebutuhan empat gelas.","perkalian"],
  [6,"diskon","Menghitung harga setelah diskon","Pecahan","Membedakan potongan harga dan harga akhir.","Hitung bagian harga yang dipotong, lalu kurangi dari harga awal. Potongan bukan harga yang dibayar.","Buat label harga dan hitung potongan seperempatnya dengan kertas uang buatan.","persen"],
  [6,"bilangan-negatif","Bergerak melewati nol","Bilangan","Memahami bilangan negatif sebagai posisi di bawah nol.","Nol adalah acuan. Bergerak ke kiri pada garis bilangan mengurangi nilai, termasuk melewati nol.","Gambar garis dari −5 sampai 5 dan lakukan gerak maju atau mundur.","mengurangi"],
  [6,"urutan-operasi","Mengelompokkan operasi","Operasi","Memahami fungsi tanda kurung dan urutan operasi.","Selesaikan bagian di dalam kurung lebih dahulu. Tanpa kurung, perkalian dikerjakan sebelum penjumlahan.","Bandingkan dua kelompok berisi tiga ditambah satu dengan tiga kelompok lalu tambah satu benda.","perkalian"],
  [6,"median","Menemukan nilai tengah","Data","Mengurutkan data sebelum menentukan median.","Median adalah nilai di tengah data yang sudah diurutkan. Bukan otomatis data yang ditulis di tengah.","Tulis lima bilangan pada kartu, urutkan, lalu temukan kartu tengah.","diagram"],
];
export const lessons: Lesson[] = definitions.map(([grade,id,title,domain,objective,concept,offline,prerequisite]) => ({grade,id,title,domain,objective,concept,offline,prerequisite}));
export const gradeDescriptions = ["Benda, bilangan, dan bentuk", "Nilai tempat dan ukuran", "Kelompok, bagian, dan data", "Hubungan bilangan dan bangun", "Pecahan, ruang, dan rata-rata", "Hubungan, operasi, dan keputusan"];
export function getLesson(id: string): Lesson { const lesson = lessons.find(l => l.id === id); if (!lesson) throw new Error("Materi tidak ditemukan."); return lesson; }
