import { getLesson } from "./catalog.ts";
export interface Model { kind: "counters" | "groups" | "fraction" | "grid" | "bars" | "polygon" | "line" | "place" | "text"; values: number[]; labels: string[]; summary: string; }
export interface Question { lessonId: string; seed: number; prompt: string; unit: string; expected: number; explanation: string; reasons: string[]; correctReason: number; hints: string[]; model: Model; }
export interface Evaluation { answerCorrect: boolean; reasonCorrect: boolean; independent: boolean; feedback: string; }
export function generateQuestion(lessonId: string, seed: number): Question {
  const lesson = getLesson(lessonId);
  if (!Number.isInteger(seed) || seed < 0 || seed > 2147483647) throw new Error("Seed tidak valid.");
  let state = (seed + 1) >>> 0;
  const pick = (min: number,max: number) => { state = (Math.imul(state,1664525)+1013904223) >>> 0; return min + state % (max-min+1); };
  let a = pick(2,5), b = pick(2,4), c = pick(2,3), expected = 0, prompt = "", unit = "", explanation = "", reason = "", wrong = ["Urutan benda mengubah banyaknya.","Gunakan angka pertama saja."], help = "";
  let model: Model = {kind:"text",values:[],labels:[],summary:""};
  const set = (kind: Model["kind"],values: number[],labels: string[],summary: string) => { model = {kind,values,labels,summary}; };
  switch (lessonId) {
    case "menghitung": expected=a+b; prompt="Berapa banyak benda dalam kelompok ini?"; set("counters",[expected],["Kelompok benda"],"Satu kelompok benda. Hitung setiap lingkaran satu kali."); explanation=`Ada ${expected} benda. Bilangan terakhir menyatakan banyaknya.`; reason="Setiap benda dihitung satu kali."; help="Sentuh atau tunjuk benda dari kiri ke kanan."; break;
    case "menjumlah": expected=a+b; prompt=`Ada ${a} benda, lalu datang ${b} benda. Berapa semuanya?`; set("counters",[a,b],["Awal","Datang"],`${a} benda awal dan ${b} benda datang; kedua kelompok digabung.`); explanation=`${a} + ${b} = ${expected}. Kedua kelompok dihitung.`; reason="Dua kelompok digabung tanpa menghilangkan benda."; wrong=["Kelompok kedua diambil dari kelompok pertama.","Hanya benda yang datang dihitung."]; help=`Mulai dari ${a}, lalu hitung ${b} benda tambahan.`; break;
    case "mengurangi": a=a+b; expected=a-b; prompt=`Ada ${a} benda. ${b} diambil. Berapa yang tersisa?`; set("counters",[a,b],["Awal","Diambil"],`Mulai dengan ${a} benda; ${b} diambil dari kelompok awal. Gambar kedua menunjukkan benda yang diambil, bukan tambahan.`); explanation=`${a} − ${b} = ${expected}. Yang diambil tidak termasuk sisa.`; reason="Benda yang diambil dikeluarkan dari kelompok awal."; wrong=["Benda yang diambil ditambahkan.","Semua benda awal masih tersisa."]; help=`Hitung mundur ${b} langkah dari ${a}.`; break;
    case "membandingkan": b=a+pick(1,4); expected=b-a; prompt=`Kelompok kedua memiliki berapa benda lebih banyak?`; set("counters",[a,b],["Pertama","Kedua"],`Kelompok pertama ${a} benda, kedua ${b} benda. Cari selisihnya.`); explanation=`Selisihnya ${b} − ${a} = ${expected}.`; reason="Pasangkan benda satu-satu; benda yang tidak berpasangan adalah selisih."; wrong=["Gabungkan semua benda untuk mencari selisih.","Jawab dengan banyak benda kelompok kedua."]; help="Pasangkan satu benda pertama dengan satu benda kedua."; break;
    case "bangun": a=pick(3,4); expected=a; prompt="Berapa sisi lurus bangun ini?"; set("polygon",[a],[],a===3?"Segitiga memiliki tiga ruas lurus yang membentuk tepinya.":"Persegi memiliki empat ruas lurus yang membentuk tepinya."); explanation=`Bangun ini memiliki ${a} sisi lurus.`; reason="Hitung setiap ruas tepi satu kali."; wrong=["Hitung bidang di dalam bangun.","Hitung semua titik di kertas."]; help="Ikuti tepi bangun dari satu pojok sampai kembali."; break;
    case "nilai-tempat": expected=10*a+b; prompt=`Berapa nilai ${a} puluhan dan ${b} satuan?`; set("place",[a,b],["Puluhan","Satuan"],`${a} kelompok sepuluh dan ${b} satuan lepas.`); explanation=`${a} × 10 + ${b} = ${expected}.`; reason="Setiap puluhan bernilai sepuluh, setiap satuan bernilai satu."; wrong=["Setiap puluhan hanya bernilai satu.","Tukar urutan digit satuan dan puluhan."]; help=`${a} puluhan sama dengan ${a*10}. Tambahkan satuannya.`; break;
    case "tambah-puluhan": a=pick(21,48); b=pick(13,29); expected=a+b; prompt=`Berapa ${a} + ${b}?`; set("text",[a,b],["Kelompok pertama","Kelompok kedua"],`${a} dan ${b} dapat diurai menjadi puluhan dan satuan.`); explanation=`${Math.floor(a/10)*10} + ${a%10} + ${Math.floor(b/10)*10} + ${b%10} = ${expected}.`; reason="Jumlahkan menurut nilai tempat; sepuluh satuan menjadi satu puluhan."; wrong=["Gabungkan digit tanpa menjumlahkan nilainya.","Satuan boleh diabaikan."]; help=`Jumlahkan ${a%10} dan ${b%10} satuan dahulu, lalu gabungkan puluhan.`; break;
    case "kurang-puluhan": a=pick(41,69); b=pick(12,29); expected=a-b; prompt=`Berapa ${a} − ${b}?`; set("text",[a,b],["Awal","Diambil"],`Kurangi ${b} dari ${a}; nilai tempat tetap dipertahankan.`); explanation=`${a} − ${Math.floor(b/10)*10} − ${b%10} = ${expected}.`; reason="Kurangi puluhan dan satuan; satu puluhan dapat diurai menjadi sepuluh satuan."; wrong=["Kurangi digit besar dengan digit kecil tanpa memperhatikan tempat.","Tambahkan kedua bilangan."]; help=`Kurangi ${Math.floor(b/10)*10} dahulu, lalu ${b%10} lagi.`; break;
    case "waktu": a=pick(7,10); b=pick(1,3); expected=b; prompt=`Kegiatan mulai pukul ${a}.00 dan selesai pukul ${a+b}.00. Berapa jam lamanya?`; unit="jam"; set("line",[a,a+b],["Mulai","Selesai"],`Dari jam ${a} ke jam ${a+b}, dalam hari yang sama.`); explanation=`${a+b} − ${a} = ${b} jam.`; reason="Lama kegiatan adalah selisih waktu selesai dan mulai."; wrong=["Lama kegiatan adalah angka jam selesai.","Jumlahkan kedua jam."]; help="Hitung pergantian jam, bukan jumlah tanda jam yang disentuh."; break;
    case "panjang": expected=a+b; unit="cm"; prompt="Setiap kotak panjangnya 1 cm. Berapa panjang pita?"; set("grid",[expected,1],["Panjang pita"],`Pita terdiri dari ${expected} unit berurutan, masing-masing 1 cm, tanpa celah.`); explanation=`${expected} unit × 1 cm = ${expected} cm.`; reason="Jumlah unit sama panjang menunjukkan panjang pita."; wrong=["Celah antarunit ikut ditambahkan.","Ukuran unit tidak perlu sama."]; help="Hitung kotak unit, bukan garis batasnya."; break;
    case "perkalian": expected=a*b; prompt=`Ada ${a} kelompok, tiap kelompok berisi ${b}. Berapa semua benda?`; set("groups",[a,b],["Kelompok sama besar"],`${a} kelompok, masing-masing ${b} benda.`); explanation=`${a} × ${b} = ${expected}, atau ${Array(a).fill(b).join(" + ")}.`; reason="Isi tiap kelompok dijumlahkan sebanyak jumlah kelompok."; wrong=["Jumlah kelompok cukup ditambah isi satu kelompok.","Hanya satu kelompok dihitung."]; help=`Jumlahkan ${b} sebanyak ${a} kali.`; break;
    case "pembagian": expected=b; prompt=`${a*b} benda dibagi rata ke ${a} kelompok. Berapa isi tiap kelompok?`; set("counters",[a*b],["Benda yang akan dibagi"],`${a*b} benda akan dibagi rata ke ${a} kelompok.`); explanation=`${a*b} ÷ ${a} = ${b}. Tiap kelompok mendapat ${b}.`; reason="Seluruh benda dibagi sama banyak ke setiap kelompok."; wrong=["Tiap kelompok mendapat seluruh benda.","Cukup kurangi jumlah kelompok dari total."]; help=`Cari bilangan yang jika dikali ${a} menghasilkan ${a*b}.`; break;
    case "pecahan": a=pick(1,3); b=4; expected=a; prompt="Bagian berarsir ditulis …/4. Berapa pembilangnya?"; set("fraction",[a,b],["Satu utuh"],`${a} dari ${b} bagian sama besar berarsir.`); explanation=`${a} bagian dipilih dari ${b} bagian; pecahannya ${a}/${b}.`; reason="Pembilang menghitung bagian yang dipilih."; wrong=["Pembilang selalu menghitung semua bagian.","Pembilang menghitung bagian yang tidak dipilih."]; help="Hitung bagian bertanda garis, bukan seluruh bagian."; break;
    case "keliling": expected=2*(a+b); unit="cm"; prompt=`Panjang ${a} cm, lebar ${b} cm. Berapa kelilingnya?`; set("grid",[a,b],["Persegi panjang"],`Persegi panjang: panjang ${a} cm dan lebar ${b} cm; tiap kotak 1 cm persegi.`); explanation=`${a} + ${b} + ${a} + ${b} = ${expected} cm.`; reason="Keliling menjumlahkan panjang keempat sisi."; wrong=["Keliling menghitung semua kotak di dalam.","Hanya dua sisi dijumlahkan."]; help="Telusuri atas, kanan, bawah, kiri."; break;
    case "diagram": a=pick(2,5); b=a+pick(1,3); expected=b-a; prompt="Berapa selisih banyak buku dan pensil?"; set("bars",[a,b],["Pensil","Buku"],`Pensil ${a}, buku ${b}. Satu unit batang mewakili satu benda.`); explanation=`Selisihnya ${b} − ${a} = ${expected}.`; reason="Selisih data diperoleh dengan mengurangi banyak yang lebih besar dengan yang lebih kecil."; wrong=["Selisih diperoleh dengan menjumlahkan kedua batang.","Lebar batang menentukan banyak benda."]; help="Cari bagian tinggi batang yang tidak sama."; break;
    case "pecahan-senilai": a=pick(1,3); expected=a*2; prompt=`${a}/4 = …/8. Berapa pembilang barunya?`; set("fraction",[a,4],["Satu utuh"],`${a} dari empat bagian sama besar dipilih; tiap bagian akan dibagi dua lagi.`); explanation=`${a}/4 = ${a*2}/8. Pembilang dan penyebut sama-sama dikali dua.`; reason="Pembilang dan penyebut dikali bilangan yang sama."; wrong=["Hanya penyebut diubah.","Tambahkan empat pada pembilang."]; help="Setiap bagian lama berubah menjadi dua bagian kecil."; break;
    case "luas": expected=a*b; unit="cm²"; prompt=`Setiap kotak luasnya 1 cm². Berapa luas persegi panjang?`; set("grid",[a,b],["Persegi satuan"],`${b} baris dengan ${a} kotak per baris; setiap kotak 1 cm persegi.`); explanation=`${b} baris × ${a} kotak = ${expected} cm².`; reason="Luas menghitung kotak satuan yang menutup permukaan."; wrong=["Luas hanya menjumlahkan panjang tepi.","Hitung garis di antara kotak saja."]; help=`Ada ${b} baris. Berapa kotak dalam tiap baris?`; break;
    case "sudut": c=pick(1,3); expected=90*c; unit="derajat"; prompt=`Berapa derajat ${c===1?"seperempat":c===2?"setengah":"tiga perempat"} putaran penuh?`; set("text",[360,c,4],["Derajat satu putaran","Bagian dipilih","Seluruh bagian"],`Satu putaran 360 derajat dibagi empat sama besar. Ambil ${c} bagiannya.`); explanation=`360 ÷ 4 × ${c} = ${expected} derajat.`; reason="Bagi besar putaran penuh menjadi empat, lalu ambil bagian yang diminta."; wrong=["Setiap bagian sama dengan satu putaran penuh.","Satu bagian putaran hanya sebesar satu derajat."]; help=`Seperempat putaran adalah 90 derajat. Ambil ${c} bagian seperempat.`; break;
    case "faktor": expected=b; prompt=`${a*b} benda disusun dalam ${a} baris sama banyak. Berapa benda tiap baris?`; set("counters",[a*b],["Benda yang disusun"],`${a*b} benda akan disusun menjadi ${a} baris tanpa sisa.`); explanation=`${a} × ${b} = ${a*b}; ${a} dan ${b} adalah pasangan faktor.`; reason="Pasangan faktor jika dikalikan menghasilkan bilangan semula."; wrong=["Pasangan faktor jika dijumlahkan menghasilkan bilangan semula.","Boleh ada sisa benda."]; help=`Cari pasangan perkalian ${a} × … = ${a*b}.`; break;
    case "satuan": expected=a*100; unit="cm"; prompt=`${a} meter sama dengan berapa sentimeter?`; set("text",[a,100],["Meter","Sentimeter per meter"],`${a} meter, tiap meter 100 sentimeter.`); explanation=`${a} × 100 = ${expected} cm.`; reason="Setiap meter memuat seratus sentimeter."; wrong=["Mengganti unit mengubah panjang bendanya.","Satu meter sama dengan sepuluh sentimeter."]; help="Ubah setiap meter menjadi 100 cm, lalu jumlahkan."; break;
    case "desimal": a=pick(1,9); expected=a/10; prompt=`Tuliskan ${a}/10 sebagai desimal.`; set("fraction",[a,10],["Persepuluhan"],`${a} dari sepuluh bagian sama besar dipilih.`); explanation=`${a}/10 = 0,${a}.`; reason="Digit pertama setelah koma menyatakan persepuluhan."; wrong=["Pembilang ditulis sebagai bilangan utuh.","Persepuluhan ditulis sebagai perseratus."]; help="Gunakan koma atau titik. Satu persepuluh ditulis 0,1."; break;
    case "tambah-pecahan": expected=a+b; prompt=`${a}/12 + ${b}/12 = …/12. Berapa pembilang hasilnya?`; set("fraction",[a,12,b],["Bagian pertama","Bagian kedua"],`${a} bagian dan ${b} bagian dari dua belas; ukuran satu utuh sama.`); explanation=`${a}/12 + ${b}/12 = ${a+b}/12.`; reason="Ukuran bagian sama, sehingga pembilang dijumlahkan dan penyebut tetap."; wrong=["Pembilang dan penyebut sama-sama dijumlahkan.","Jumlahkan penyebut saja."]; help=`Gabungkan ${a} bagian dengan ${b} bagian yang berukuran sama.`; break;
    case "volume": expected=a*b*c; unit="cm³"; prompt=`Kotak panjang ${a}, lebar ${b}, tinggi ${c} cm. Berapa volumenya?`; set("grid",[a,b,c],["Satu lapisan"],`Satu lapisan ${a} kali ${b} kubus satuan; ada ${c} lapisan. Gambar menampilkan satu lapisan saja.`); explanation=`${a} × ${b} × ${c} = ${expected} cm³.`; reason="Kubus dalam satu lapisan dikalikan banyak lapisan."; wrong=["Jumlahkan ketiga ukuran saja.","Hitung satu lapisan saja tanpa tinggi."]; help=`Satu lapisan memuat ${a*b} kubus. Ada ${c} lapisan.`; break;
    case "persen": a=pick(1,3)*25; expected=a; unit="persen"; prompt=`${a} dari 100 bagian dipilih. Berapa persennya?`; set("fraction",[a/25,4],["Satu utuh"],`${a} dari 100 bagian dipilih; gambar disederhanakan menjadi empat bagian, masing-masing 25 persen.`); explanation=`${a}/100 = ${a}%.`; reason="Persen menyatakan banyak bagian per seratus."; wrong=["Persen selalu menyatakan banyak bagian per sepuluh.","Persen menghitung hanya bagian tidak dipilih."]; help="Per seratus dan persen menyatakan ukuran bagian yang sama."; break;
    case "rata-rata": a=pick(3,6); expected=a; prompt="Berapa rata-rata banyak benda pada ketiga kelompok?"; set("bars",[a-2,a,a+2],["A","B","C"],`Tiga kelompok berisi ${a-2}, ${a}, ${a+2} benda.`); explanation=`(${a-2} + ${a} + ${a+2}) ÷ 3 = ${a}.`; reason="Jumlah semua nilai dibagi banyak data."; wrong=["Gunakan hanya nilai terbesar.","Jumlahkan nilai tanpa membagi banyak data."]; help="Bayangkan memindahkan benda dari kelompok paling banyak ke paling sedikit."; break;
    case "perbandingan": expected=b*c; prompt=`${a} gelas minuman membutuhkan ${b} sendok sirup. Berapa sendok untuk ${a*c} gelas dengan rasa sama?`; set("text",[a,b,a*c],["Gelas awal","Sendok awal","Gelas baru"],`Jumlah gelas bertambah ${c} kali; rasanya dijaga tetap sama.`); explanation=`Gelas menjadi ${c} kali; sirup ${b} × ${c} = ${expected} sendok.`; reason="Kedua besaran dikalikan faktor yang sama agar perbandingan tetap."; wrong=["Tambah jumlah gelas baru pada sirup awal.","Sirup tetap sama walau gelas bertambah."]; help=`${a*c} gelas adalah ${c} kali ${a} gelas.`; break;
    case "diskon": a=pick(2,8)*10000; b=25; expected=a*0.75; unit="rupiah"; prompt=`Harga Rp${a.toLocaleString("id-ID")}, diskon 25%. Berapa harga setelah diskon?`; set("fraction",[1,4],["Bagian harga yang dipotong"],"Seperempat harga dipotong. Tiga perempat harga masih dibayar."); explanation=`Potongan ${a}/4 = ${a/4}; harga akhir ${a} − ${a/4} = ${expected}.`; reason="Harga akhir adalah harga awal dikurangi potongan."; wrong=["Harga akhir sama dengan besar potongannya.","Diskon ditambahkan ke harga awal."]; help="Cari seperempat harga, lalu kurangi dari harga awal. Tulis angka tanpa pemisah ribuan."; break;
    case "bilangan-negatif": a=pick(1,4); b=a+pick(1,4); expected=a-b; prompt=`Mulai dari ${a}, mundur ${b} langkah. Di angka berapa berhenti?`; set("line",[a,a-b],["Mulai","Arah mundur"],`Mulai di ${a} pada garis bilangan; bergerak ke kiri ${b} langkah, melewati nol.`); explanation=`${a} − ${b} = ${expected}. Posisi akhir di kiri nol.`; reason="Mundur pada garis bilangan mengurangi nilai, juga saat melewati nol."; wrong=["Bilangan berhenti berkurang ketika mencapai nol.","Mundur selalu menambah nilai."]; help="Setelah nol, satu langkah ke kiri adalah −1."; break;
    case "urutan-operasi": expected=(a+b)*c; prompt=`Berapa (${a} + ${b}) × ${c}?`; set("groups",[c,a+b],["Kelompok berisi hasil penjumlahan"],`${c} kelompok, masing-masing memiliki ${a} ditambah ${b} benda.`); explanation=`(${a} + ${b}) × ${c} = ${a+b} × ${c} = ${expected}.`; reason="Penjumlahan di dalam tanda kurung dikerjakan terlebih dahulu."; wrong=["Abaikan kurung dan kalikan hanya bilangan kedua.","Jumlahkan semua bilangan tanpa perkalian."]; help="Cari isi satu kelompok terlebih dahulu."; break;
    case "median": a=pick(5,9); expected=a; prompt="Berapa median data berikut?"; set("text",[a,a-2,a+3,a+1,a-4],["Data 1","Data 2","Data 3","Data 4","Data 5"],`Data ${a}, ${a-2}, ${a+3}, ${a+1}, ${a-4}; belum diurutkan.`); explanation=`Urutan ${a-4}, ${a-2}, ${a}, ${a+1}, ${a+3}. Nilai ketiga adalah ${a}.`; reason="Urutkan data dahulu, lalu pilih nilai tengah."; wrong=["Pilih angka terbesar.","Jumlah semua data adalah median."]; help="Tuliskan dari nilai terkecil ke terbesar; ada lima data."; break;
    default: throw new Error("Generator belum tersedia.");
  }
  const correctReason=pick(0,2); const reasons=[...wrong]; reasons.splice(correctReason,0,reason);
  return {lessonId,seed,prompt,unit,expected,explanation,reasons,correctReason,model,hints:[lesson.concept,help,explanation]};
}
export function parseAnswer(value: string): number | null {
  const text=value.trim(); if (!/^-?\d+(?:[.,]\d+)?$/.test(text) || text.length>20) return null;
  const number=Number(text.replace(",",".")); return Number.isFinite(number)?number:null;
}
export function evaluateQuestion(question: Question, answer: string, reasonIndex: number, hintsUsed: number, attemptNumber=1): Evaluation {
  const parsed=parseAnswer(answer); const answerCorrect=parsed!==null && Math.abs(parsed-question.expected)<1e-9;
  const reasonCorrect=reasonIndex===question.correctReason;
  return {answerCorrect,reasonCorrect,independent:answerCorrect&&reasonCorrect&&hintsUsed===0&&attemptNumber===1,feedback:answerCorrect&&reasonCorrect?`Ya. ${question.explanation}`:answerCorrect?"Jawabannya tepat. Periksa lagi alasan yang menjelaskan hubungan matematika.":"Belum tepat. Lihat model dan gunakan petunjuk jika perlu."};
}
