import { useEffect, useState } from "preact/hooks";
import { api, type Session, type Profile } from "../../lib/account/api";
export default function Family() {
  const [session,setSession]=useState<Session|null>(null),[loaded,setLoaded]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Profile|null>(null),[notice,setNotice]=useState("");
  function load(){ setError(""); api<Session>("/api/session").then(setSession).catch(e=>setError(e.message)).finally(()=>setLoaded(true)); }
  useEffect(load,[]);
  async function action(task:()=>Promise<void>){if(busy)return;setBusy(true);setError("");try{await task();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function submit(event:SubmitEvent){event.preventDefault();const form=event.currentTarget as HTMLFormElement;const data=new FormData(form);await action(async()=>{setSession(await api<Session>("/api/profiles",editing?"PATCH":"POST",{profileId:editing?.id,nickname:data.get("nickname"),grade:Number(data.get("grade"))}));setEditing(null);form.reset();setNotice("Profil tersimpan. Pilih profil untuk mulai belajar.");});}
  if(!loaded)return <p role="status">Memuat keluarga…</p>;
  if(!session?.user)return <section><p role="alert" class="error">{error}</p><h2>Belajar bisa dimulai tanpa akun.</h2><p>Masuk untuk membuat profil anak dan menyimpan catatan di server ini.</p><div class="actions"><a class="button" href="/masuk">Masuk</a><a href="/daftar">Buat akun</a><button onClick={load}>Coba lagi</button></div></section>;
  return <div class="section-stack"><section><div class="section-heading"><div><h2>Keluarga {session.user.name}</h2><p class="muted">{session.user.email}</p></div><button class="quiet" disabled={busy} onClick={()=>action(async()=>{await api("/api/auth/logout","POST",{});window.location.assign("/");})}>Keluar</button></div>
    <p>Pilih profil sebelum belajar. Semua kelas tetap dapat dibuka; kelas profil hanya membantu memilih titik awal.</p>
    <p role="alert" class="error">{error}</p><p role="status">{notice}</p>
    <ul class="profile-list">{session.profiles.map(profile=><li key={profile.id}><div><h3>{profile.nickname}</h3><p>Kelas {profile.grade}{session.activeProfileId===profile.id?" · Profil aktif":""}</p></div><div class="actions"><button disabled={busy} onClick={()=>action(async()=>{await api("/api/profiles/active","POST",{profileId:profile.id});window.location.assign(`/belajar/kelas-${profile.grade}`);})}>Belajar</button><button class="quiet" disabled={busy} onClick={()=>{setEditing(profile);setNotice("");}}>Ubah profil</button></div></li>)}</ul>
    {!session.profiles.length&&<p>Belum ada profil anak. Buat satu menggunakan nama panggilan saja.</p>}
    <a href="/progres">Lihat catatan belajar</a></section>
    <section class="narrow"><h2>{editing?"Ubah profil":"Tambah profil anak"}</h2><p class="muted">Tidak perlu nama lengkap, tanggal lahir, atau sekolah. Maksimal enam profil.</p>
    <form key={editing?.id??"new"} class="form-stack" onSubmit={submit} aria-busy={busy}><label>Nama panggilan<input name="nickname" defaultValue={editing?.nickname??""} minLength={2} maxLength={32} required/></label><div class="field"><label for="profile-grade">Kelas</label><select id="profile-grade" name="grade" defaultValue={editing?.grade??1}>{[1,2,3,4,5,6].map(n=><option value={n}>Kelas {n}</option>)}</select></div><div class="actions"><button disabled={busy}>{busy?"Menyimpan…":editing?"Simpan profil":"Tambah profil"}</button>{editing&&<button type="button" class="quiet" onClick={()=>setEditing(null)}>Batal</button>}</div></form></section>
    <section class="narrow"><h2>Pengaturan akun</h2><details><summary>Ubah kata sandi</summary><form class="form-stack" onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const data=new FormData(form);void action(async()=>{setSession(await api<Session>("/api/account/password","POST",{currentPassword:data.get("current"),password:data.get("new")}));form.reset();setNotice("Kata sandi diubah. Sesi perangkat lain telah diakhiri.");});}}><label>Kata sandi saat ini<input name="current" type="password" autoComplete="current-password" required maxLength={128}/></label><label>Kata sandi baru<input name="new" type="password" autoComplete="new-password" minLength={15} maxLength={128} required/></label><button disabled={busy}>Ubah kata sandi</button></form></details>
    <div class="actions"><button class="quiet" disabled={busy} onClick={()=>action(async()=>{const data=await api("/api/export");const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download="catatan-pahamhitung.json";link.click();URL.revokeObjectURL(url);})}>Unduh data keluarga</button></div>
    <details><summary>Hapus akun dan data</summary><p>Akun, profil, dan catatan di server ini akan dihapus permanen. Unduh data terlebih dahulu jika ingin menyimpannya.</p><form class="form-stack" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);void action(async()=>{await api("/api/account","DELETE",{confirmation:data.get("confirmation"),password:data.get("password")});window.location.assign("/");});}}><label>Ketik email akun<input name="confirmation" type="email" required autoComplete="off"/></label><label>Kata sandi<input name="password" type="password" required maxLength={128} autoComplete="current-password"/></label><button class="danger" disabled={busy}>Hapus permanen</button></form></details></section>
  </div>;
}
