export type ExplainStrategyFamily = "count-all" | "count-on" | "make-ten";
export type StrategyChoice = ExplainStrategyFamily;
export type ExplainStrategyInputMethod = "pointer" | "keyboard" | "switch";
export type ExplainStrategyOutcome = "target" | "alternative-valid" | "not-yet";
export interface ExplainStrategyProblem { id: string; phase: "A"; concept: "explain-strategy"; seed: number; family: ExplainStrategyFamily; addends: readonly [number, number]; total: number; equation: { left: number; operator: "+"; right: number; equals: "="; result: number }; representation: { kind: "counters" | "number-line" | "ten-frame"; addends: readonly [number, number]; total: number }; choices: readonly { id: StrategyChoice; label: string; explanation: string }[]; targetStrategy: StrategyChoice; }
export interface ExplainStrategyHint { level: 1 | 2 | 3 | 4 | 5; kind: "attention" | "question" | "representation" | "partial-step" | "worked-reasoning"; content: string; }
export type ExplainStrategyIntent = { type: "select-strategy"; value: StrategyChoice; input: ExplainStrategyInputMethod } | { type: "submit" } | { type: "request-hint" };
export interface ExplainStrategyViewState { selectedStrategy?: StrategyChoice; attempts: number; revealedHintLevels: Array<1 | 2 | 3 | 4 | 5>; activeHint?: ExplainStrategyHint; feedback?: { tone: "neutral" | "correct"; message: string }; outcome?: ExplainStrategyOutcome; complete: boolean; inputMethods: ExplainStrategyInputMethod[]; observations: Array<{ selected: StrategyChoice; outcome: ExplainStrategyOutcome }>; announcement: string; }
export interface ExplainStrategyAttemptEvidence { activityId: string; seed: number; family: ExplainStrategyFamily; addends: readonly [number, number]; total: number; targetStrategy: StrategyChoice; selectedStrategy?: StrategyChoice; outcome?: ExplainStrategyOutcome; correct: boolean; attempts: number; hintsUsed: number; highestHintLevel: 0 | 1 | 2 | 3 | 4 | 5; representationUsed: "strategy-representation"; inputMethods: ExplainStrategyInputMethod[]; responseTimeMs?: number; masteryEvidence: "not-yet" | "supported" | "developing" | "independent"; recordedAt: string; }
