import { useEffect,useRef,useState } from "preact/hooks";
import { generateChallenge,transition,evaluateChallenge,type Action,type Phase } from "../../learning/cpa/engine";
import { parseAnswer } from "../../learning/curriculum/engine";
import { readCPAEvidence,saveCPAEvidence,type CPAEvidence } from "../../lib/storage/cpa-evidence";
import CPAPicture from "./CPAPicture";
import "../../styles/cpa.css";

const phaseNames={concrete:"Benda",pictorial:"Gambar",abstract:"Simbol"};
export default function CPAGame({gameId}:{gameId:string}){
  const [seed,setSeed]=useState(0),[phase,setPhase]=useState<Phase>("concrete"),[visited,setVisited]=useState<Phase[]>(["concrete"]);
  const q=generateChallenge(gameId,seed);
  const [state,setState]=useState(q.initial),[physical,setPhysical]=useState(false),[moves,setMoves]=useState(0),[checks,setChecks]=useState(0),[hints,setHints]=useState(0),[answer,setAnswer]=useState(""),[reason,setReason]=useState(-1),[feedback,setFeedback]=useState(""),[error,setError]=useState(""),[saved,setSaved]=useState(""),[source,setSource]=useState(0),[records,setRecords]=useState<CPAEvidence[]>([]),[showPicture,setShowPicture]=useState(false),[pictureHelp,setPictureHelp]=useState(false);
  const heading=useRef<HTMLHeadingElement>(null),focusNext=useRef(false);
  useEffect(()=>{setRecords(readCPAEvidence());},[]);
  useEffect(()=>{if(focusNext.current){heading.current?.focus();focusNext.current=false;}},[phase,seed]);
  function navigate(next:Phase){focusNext.current=next!==phase;setPhase(next);setVisited(v=>v.includes(next)?v:[...v,next]);setFeedback("");setError("");}
  function act(action:Action){const next=transition(q,state,action);if(next!==state){setState(next);setMoves(m=>Math.min(10000,m+1));setFeedback("");setError("");}}
  function record(){
    const result=evaluateChallenge(q,state,answer,reason),count=Math.min(10000,checks+1);setChecks(count);
    const item:CPAEvidence={version:1,id:crypto.randomUUID(),gameId,seed,phase,visited,physicalReported:physical,pictureReopened:pictureHelp,state:[...state],moves,hints,checks:count,answer,reason,constructionCorrect:result.constructionCorrect,answerCorrect:result.answerCorrect,reasonCorrect:result.reasonCorrect,created:Date.now()};
    const ok=saveCPAEvidence(item);setSaved(ok?"Percobaan tersimpan hanya di browser ini.":"Penyimpanan browser tidak tersedia; percobaan belum disimpan. Kamu tetap bisa belajar.");if(ok)setRecords(readCPAEvidence());
    setFeedback(phase==="abstract"?result.feedback:result.constructionCorrect?"Susunannya sesuai. Sekarang hubungkan benda yang sama dengan gambar dan simbol.":"Susunannya belum sesuai. Periksa petunjuk susunan; jumlah dan hubungan tiap kelompok perlu cocok.");
  }
  function nextExample(){const nextSeed=seed===2147483647?0:seed+1,next=generateChallenge(gameId,nextSeed);focusNext.current=true;setSeed(nextSeed);setPhase("concrete");setVisited(["concrete"]);setState(next.initial);setPhysical(false);setMoves(0);setChecks(0);setHints(0);setAnswer("");setReason(-1);setFeedback("");setError("");setSaved("");setSource(0);setShowPicture(false);setPictureHelp(false);}
  const changeButton=(index:number,delta:1|-1,label:string)=><button type="button" class="quiet" disabled={transition(q,state,{type:"change",index,delta})===state} onClick={()=>act({type:"change",index,delta})}>{label}</button>;
  return <section class="cpa-game" aria-label="Permainan CPA"><p class="muted">Contoh {seed+1}. Bebas kembali ke representasi yang membantu; tidak ada batas waktu.</p>
    <nav class="cpa-phases" aria-label="Representasi CPA">{(["concrete","pictorial","abstract"] as Phase[]).map(p=><button key={p} type="button" class="quiet" aria-current={phase===p?"step":undefined} onClick={()=>navigate(p)}>{phaseNames[p]}</button>)}</nav>
    <h2 ref={heading} tabIndex={-1}>{phase==="concrete"?"C — Coba dengan benda":phase==="pictorial"?"P — Hubungkan dengan gambar":"A — Jelaskan dengan simbol"}</h2>
    <p class="cpa-prompt">{q.prompt}</p>
    {phase==="concrete"&&<><h3>Kegiatan benda nyata</h3><p>{q.concrete}</p><p class="muted">Gunakan benda aman bersama pendamping. Aktivitas fisik tidak dapat diperiksa oleh aplikasi.</p><label class="cpa-check"><input type="checkbox" checked={physical} onChange={e=>setPhysical(e.currentTarget.checked)}/>Saya sudah mencoba benda nyata (laporan sendiri, opsional).</label>
      <h3>Coba juga manipulatif digital</h3><p>Objek layar adalah model, bukan pengganti pengalaman menyentuh benda nyata. Gunakan Tab lalu Enter/Space; tidak perlu menyeret.</p>
      {q.mode==="select"?<div class="cpa-strip cpa-strip--interactive" style={{gridTemplateColumns:`repeat(${q.columns},minmax(0,1fr))`}}>{state.map((n,i)=><button key={i} type="button" class={n?"quiet cpa-cell cpa-cell--selected":"quiet cpa-cell"} aria-label={`Unit ${i+1}`} aria-pressed={!!n} onClick={()=>act({type:"change",index:i,delta:n?-1:1})}>{n?"/":"·"}</button>)}</div>:
      q.mode==="exchange"?<><CPAPicture question={q} state={state}/><div class="actions"><button class="quiet" disabled={state[1]!<10} onClick={()=>act({type:"exchange",split:false})}>Ikat 10 satuan</button><button class="quiet" disabled={state[0]===0||state[1]!+10>q.limit} onClick={()=>act({type:"exchange",split:true})}>Buka 1 puluhan</button></div><p>Nilai total: {state[0]!*10+state[1]!}. Pertukaran tidak menambah benda.</p></>:
      q.mode==="line"?<><CPAPicture question={q} state={state}/><div class="actions">{changeButton(0,-1,"Mundur 1 langkah")}{changeButton(0,1,"Maju 1 langkah")}</div></>:
      q.mode==="layers"?<><CPAPicture question={q} state={state}/><div class="actions">{changeButton(0,1,"Tambah 1 lapisan")}{changeButton(0,-1,"Ambil 1 lapisan")}</div></>:
      <><CPAPicture question={q} state={state}/>{q.mode==="redistribute"&&<label>Ambil dari<select value={source} onChange={e=>setSource(Number(e.currentTarget.value))}>{q.labels.map((label,i)=><option key={i} value={i}>{label}</option>)}</select></label>}<div class="cpa-controls">{state.map((n,i)=><div key={i}><h3>{q.labels[i]}: {n}</h3><div class="actions">{q.mode==="build"?<>{changeButton(i,1,`Tambah ke ${q.labels[i]}`)}{changeButton(i,-1,`Ambil dari ${q.labels[i]}`)}</>:q.mode==="transfer"?i>0&&<><button class="quiet" disabled={state[0]===0||state[i]===q.limit} onClick={()=>act({type:"move",from:0,to:i})}>Pindah ke {q.labels[i]}</button><button class="quiet" disabled={state[i]===0} onClick={()=>act({type:"move",from:i,to:0})}>Kembalikan dari {q.labels[i]}</button></>:<button class="quiet" disabled={source===i||state[source]===0||state[i]===q.limit} onClick={()=>act({type:"move",from:source,to:i})}>Pindah ke {q.labels[i]}</button>}</div></div>)}</div></>}
      <button onClick={record}>Periksa susunan</button><p class="muted">Pemeriksaan ini menilai susunan digital, bukan mengonfirmasi kegiatan fisik.</p></>}
    {phase==="pictorial"&&<><p>{q.bridge}</p><CPAPicture question={q} state={state}/><button class="quiet" onClick={()=>navigate("abstract")}>Hubungkan ke simbol</button></>}
    {phase==="abstract"&&<><p>{q.abstractPrompt}</p><p class="cpa-equation">{gameId==="bagian"?"…/4":gameId==="senilai"?`${q.expected/2}/4 = …/8`:`${q.equation} = …`}</p><form class="form-stack" onSubmit={e=>{e.preventDefault();if(parseAnswer(answer)===null){setError("Tulis angka; desimal boleh memakai koma atau titik.");return;}if(reason<0){setError("Pilih alasan yang menghubungkan gambar dan simbol.");return;}setError("");record();}}><label>Jawaban<input value={answer} maxLength={20} inputMode={q.mode==="line"?"text":"decimal"} aria-describedby="cpa-error" onInput={e=>{setAnswer(e.currentTarget.value);setFeedback("");}}/></label><fieldset><legend>Mengapa hubungan ini tepat?</legend><div class="reason-options">{q.reasons.map((text,i)=><label key={text} class="reason-option"><input name="cpa-reason" type="radio" checked={reason===i} onChange={()=>{setReason(i);setFeedback("");}}/>{text}</label>)}</div></fieldset><button>Periksa simbol dan alasan</button></form><button class="quiet" aria-expanded={showPicture} onClick={()=>{setShowPicture(!showPicture);setPictureHelp(true);}}> {showPicture?"Sembunyikan gambar bantuan":"Tampilkan gambar bantuan"}</button>{showPicture&&<CPAPicture question={q} state={state}/>}</>}
    <p role="status" class="feedback">{feedback}</p><p id="cpa-error" role="alert" class="error">{error}</p>
    <button class="quiet" disabled={hints===3} onClick={()=>setHints(h=>h+1)}>Petunjuk {hints}/3</button>{hints>0&&<aside class="hint" aria-label="Petunjuk CPA"><h3>Petunjuk {hints}</h3><p>{q.hints[hints-1]}</p></aside>}
    <p role="status" class="muted">{saved}</p><div class="actions"><button class="quiet" onClick={nextExample}>Contoh berikutnya</button><a href="/cpa">Semua permainan CPA</a></div>
    <details class="cpa-records"><summary>Catatan CPA di perangkat ini ({records.filter(r=>r.gameId===gameId).length})</summary><p>Terpisah dari profil akun. Tidak disinkronkan. Laporan benda nyata dan penggunaan bantuan bukan bukti penguasaan. Maksimum 500 percobaan terbaru.</p><ul>{records.filter(r=>r.gameId===gameId).slice(-5).reverse().map(r=><li key={r.id}>Contoh {r.seed+1} · {phaseNames[r.phase]} · susunan {r.constructionCorrect?"sesuai":"perlu diperiksa"} · jawaban {r.answerCorrect?"tepat":"belum tepat / belum diisi"} · alasan {r.reasonCorrect?"tepat":"belum tepat / belum dipilih"} · {r.moves} perubahan · petunjuk {r.hints}/3 · gambar bantuan {r.pictureReopened?"dibuka":"tidak dibuka"} · benda nyata {r.physicalReported?"dilaporkan dicoba":"belum dilaporkan"}.</li>)}</ul></details>
  </section>;
}
