import type { Question,Model } from "../../learning/curriculum/engine";
import MathModel from "./MathModel";

// Supplemental examples only: never change the existing deterministic question engine.
export default function CPAWorkedPicture({question:q}:{question:Question}){
  const [a=0,b=0,c=0]=q.model.values;
  const place=(n:number):Model=>({kind:"place",values:[Math.floor(n/10),n%10],labels:["Puluhan","Satuan"],summary:`${n}: ${Math.floor(n/10)} puluhan dan ${n%10} satuan.`});
  if(["tambah-puluhan","kurang-puluhan"].includes(q.lessonId))return <div><h4>{q.lessonId==="tambah-puluhan"?"Kelompok pertama":"Kelompok awal"}</h4><MathModel model={place(a)}/><h4>{q.lessonId==="tambah-puluhan"?"Kelompok kedua":"Jumlah yang diambil dari kelompok awal"}</h4><MathModel model={place(b)}/><p>Setiap batang bernilai 10. {q.lessonId==="tambah-puluhan"?"Gabungkan satuan, lalu tukar setiap 10 satuan menjadi satu puluhan.":"Jika satuan kurang, buka satu batang menjadi 10 satuan sebelum mengambil."}</p></div>;
  if(q.lessonId==="sudut")return <figure class="math-model"><figcaption>Putaran {b}/4 dari satu lingkaran penuh. Setiap daerah seperempat mewakili 90°.</figcaption><svg viewBox="0 0 200 200" role="img" aria-label={`${b} seperempat putaran, ${q.expected} derajat.`}><circle cx="100" cy="100" r="80" class="cpa-turn-outline"/>{["M100 100 L100 20 A80 80 0 0 1 180 100 Z","M100 100 L180 100 A80 80 0 0 1 100 180 Z","M100 100 L100 180 A80 80 0 0 1 20 100 Z"].slice(0,b).map(path=><path key={path} d={path} class="cpa-turn-part"/>)}<path d="M100 20 V180 M20 100 H180" class="cpa-turn-outline"/></svg><p>Telusuri dari arah atas searah jarum jam. Mengubah panjang penunjuk tidak mengubah besar putarannya.</p></figure>;
  if(q.lessonId==="satuan")return <figure class="math-model"><figcaption>Panjang yang sama: {a} meter. Tiap segmen 1 m = 100 cm.</figcaption><div class="cpa-strip" style={{gridTemplateColumns:`repeat(${a},minmax(0,1fr))`}}>{Array.from({length:a},(_,i)=><span key={i} class="cpa-cell">1 m</span>)}</div><p>Bandingkan dua penamaan unit untuk panjang yang sama. Segmen tidak bertambah panjang saat ditulis 100 cm.</p></figure>;
  if(q.lessonId==="perbandingan")return <figure class="math-model"><figcaption>Gelas awal {a}, sendok awal {b}; kedua besaran diperbesar {c/a} kali.</figcaption><div class="cpa-strip" style={{gridTemplateColumns:`repeat(${c/a},minmax(0,1fr))`}}>{Array.from({length:c/a},(_,i)=><span key={i} class="cpa-cell">{a} gelas<br/>{b} sendok</span>)}</div><p>Setiap segmen adalah satu salinan resep awal; total gelas {c}, total sendok {q.expected}. Bukan {b} sendok untuk tiap gelas.</p></figure>;
  if(q.lessonId==="median")return <figure class="math-model"><figcaption>Kartu data sebelum diurutkan: {q.model.values.join(", ")}.</figcaption><div class="cpa-cards">{q.model.values.toSorted((x,y)=>x-y).map((n,i)=><span key={i} class={i===2?"cpa-number-card cpa-number-card--middle":"cpa-number-card"}>{n}<small>{i===2?"tengah":""}</small></span>)}</div><p>Setelah diurutkan, kartu ketiga memiliki dua kartu di kiri dan dua di kanan.</p></figure>;
  return <MathModel model={q.model}/>;
}
