import { useState } from "preact/hooks";
import type { Model } from "../../learning/curriculum/engine";
export default function MathModel({model}: {model:Model}) {
  const [marked,setMarked]=useState<number[]>([]); const [a=0,b=0,c=0]=model.values;
  const dot=(index:number)=><button type="button" class={`counter ${marked.includes(index)?"counter--marked":""}`} aria-label={`Benda ${index%100+1}${index>=100?`, kelompok ${Math.floor(index/100)+1}`:""}${marked.includes(index)?", sudah ditandai":""}`} aria-pressed={marked.includes(index)} onClick={()=>setMarked(marked.includes(index)?marked.filter(i=>i!==index):[...marked,index])}><span aria-hidden="true">{marked.includes(index)?"✓":""}</span></button>;
  return <figure class="math-model"><figcaption>{model.summary}</figcaption>
    {model.kind==="counters"&&<><div class="model-groups">{model.labels[1]==="Diambil"?<div><p>Kelompok awal; benda bertanda silang diambil.</p><div class="counter-grid">{Array.from({length:a},(_,i)=>i>=a-b?<span class="counter counter--taken" role="img" aria-label={`Benda ${i+1}, diambil`}>×</span>:dot(i))}</div></div>:model.values.map((n,group)=><div><p>{model.labels[group]}</p><div class="counter-grid">{Array.from({length:n},(_,i)=>dot(group*100+i))}</div></div>)}</div><p class="muted">Klik atau tekan Enter pada benda untuk menandai. Penandaan tidak mengubah jumlah.</p></>}
    {model.kind==="groups"&&<div class="model-groups">{Array.from({length:a},(_,group)=><div class="equal-group"><p>Kelompok {group+1}</p><div class="counter-grid">{Array.from({length:b},(_,i)=>dot(group*100+i))}</div></div>)}</div>}
    {model.kind==="place"&&<div class="model-groups"><div><p>{a} puluhan</p><div class="tens">{Array.from({length:a},()=> <div class="ten-rod" aria-label="Sepuluh satuan">{Array.from({length:10},()=> <span/>)}</div>)}</div></div><div><p>{b} satuan</p><div class="counter-grid">{Array.from({length:b},(_,i)=>dot(i))}</div></div></div>}
    {model.kind==="fraction"&&<div class="fraction-strip" style={{gridTemplateColumns:`repeat(${b}, minmax(0,1fr))`}} role="img" aria-label={model.summary}>{Array.from({length:b},(_,i)=><span class={i<a?"fraction-part selected":c&&i<a+c?"fraction-part second":"fraction-part"}><span class="sr-only">{i<a||c&&i<a+c?"Terpilih":"Tidak terpilih"}</span></span>)}</div>}
    {model.kind==="grid"&&<><div class="unit-grid" style={{gridTemplateColumns:`repeat(${a}, minmax(0,1fr))`}} role="img" aria-label={model.summary}>{Array.from({length:a*b},()=> <span/>)}</div>{c>0&&<p>Gambar satu lapisan. Total: {c} lapisan yang sama.</p>}</>}
    {model.kind==="polygon"&&<svg viewBox="0 0 220 160" role="img" aria-label={model.summary}>{a===3?<polygon points="110,12 20,145 200,145"/>:<rect x="30" y="12" width="150" height="135"/>}</svg>}
    {model.kind==="bars"&&<div class="data-bars">{model.values.map((n,i)=><div><span>{model.labels[i]}</span><div class="bar-units" aria-label={`${n} benda`}>{Array.from({length:n},()=> <span/>)}</div><span>{n}</span></div>)}</div>}
    {model.kind==="line"&&<><p>{b<0?"← Arah mundur":"Arah waktu maju →"}</p><div class="number-ticks" style={{gridTemplateColumns:`repeat(${b<0?11:b-a+1}, minmax(0,1fr))`}} role="img" aria-label={model.summary}>{Array.from({length:b<0?11:b-a+1},(_,i)=>{const value=b<0?i-5:a+i;return <span class={value===a?"tick tick--start":"tick"}>{value}<small>{value===a?"mulai":""}</small></span>;})}</div></>}
    {model.kind==="text"&&<dl class="math-values">{model.values.map((n,i)=><div><dt>{model.labels[i]}</dt><dd>{n.toLocaleString("id-ID")}</dd></div>)}</dl>}
  </figure>;
}
